%For loop to read all audio files in the folder 
folder = 'C:\Users\sheen\OneDrive\Desktop\252implant\audiofiles';
audio_files = dir(fullfile(folder, '*.wav'));
for i = 1:length(audio_files)
  filename = strcat(folder, '\', audio_files(i).name);
  %disp(filename);
  info = audioinfo(filename);
  %task 3.1
  [y,Fs] = audioread(filename); %Fs is the sampling rate 

  if info.SampleRate > 16000
    info = audioinfo(filename); %info.SampleRate is also sampling rate 
    [y,Fs] = audioread(filename);
    %task 3.2
    if info.NumChannels > 1
      y_mono = sum(y, 2); 
    end
    %task 3.3
    sound(y_mono, Fs); %play the mono sound 
   
    %task 3.6 
    if info.SampleRate > 16000
      downsampled_y = resample(y_mono, 16000, Fs); 
    end
    
    %task 3.4 
    new_file = strcat('New_', audio_files(i).name); 
    audiowrite(new_file, downsampled_y, 16000); 
    new_info = audioinfo(new_file); 

    %task 3.5 
    fig1 = strcat(audio_files(i).name, ' Audio Signal');
    figure('Name', fig1);
    plot(downsampled_y); 
    xlabel('Sample Number', 'FontSize', 16);
    ylabel('Audio Signal', 'FontSize', 16); 

    %task 3.7 
##    fig2 = strcat(audio_files(i).name, ' Cos Function');
##    figure('Name', fig2);
##    freq = 1000;
##    w = 2*pi*freq; 
##    step = info.Duration/info.TotalSamples; 
##    period = 1/freq;  
##    t = 0:step:2*period; 
##    plot(t, cos(w*t)); 
##    xlabel('Time','FontSize', 16); 
##    ylabel('Signal','FontSize', 16); 
##
##    t_step = 1/(info.Duration*freq); %1/number of cycles 
##    t_sound = 0:t_step:info.Duration; 
##    sound(cos(w*t_sound), 16000); %play sound generated by the signal
    %task 4 
  else 
    disp('The sampling rate of this audio file is less than 16kHz. Please choose a different file.'); 
  end
end



